import type { Locale } from "@/lib/locales"
import type { ActivityInterest, Region } from "@/lib/options"

/*
 * All site copy lives here. Voice and wording rules:
 * .cursor/rules/padeltech-voice.mdc — read it before editing.
 */

const he = {
  meta: {
    title: "PADELTECH ישראל — מתחמי פאדל לרשויות וליזמים",
    description:
      "מתחמי פאדל עם גג סולארי, רכש ישיר מהיצרן ותפעול אוטומטי. תכנון, הקמה והפעלה לרשויות, ליזמים ולמפעילים.",
  },
  nav: {
    municipalities: "לרשויות",
    developers: "ליזמים",
    operators: "למפעילים",
    projects: "פרויקטים",
    court: "המגרש",
    solution: "הפתרון",
    clubs: "המועדונים",
    about: "אודות",
    contact: "צור קשר",
    meeting: "בדיקת התאמה",
    business: "עסקים",
    players: "לשחקנים",
    company: "החברה",
    padel: "לשחק",
    club: "המועדון",
    groups: "קבוצות וארגונים",
    wellness: "הרגע שאחרי",
    story: "הסיפור",
    partners: "שותפים",
    privacy: "מדיניות פרטיות",
    main: "ניווט ראשי",
    openMenu: "פתיחת תפריט",
    closeMenu: "סגירת תפריט",
    language: "EN",
    languageLabel: "English",
  },
  cta: {
    primary: "שמרו לי מקום",
    book: "הזמינו מגרש",
    secondary: "איך זה יעבוד",
  },
  hero: {
    brand: "PADELTECH",
    eyebrow: "PADELTECH ישראל",
    title: "באים לשחק.",
    body: "PADELTECH ישראל מתכננת, מקימה ומפעילה מתחמי פאדל עם גג סולארי ותפעול אוטומטי.",
  },
  line: "זה לא המקום שבו שוכרים מגרש. זה המקום שבאים אליו לשחק.",
  experience: {
    kicker: "המועדון",
    moments: [
      {
        word: "עיצוב",
        line: "זכוכית, אור וקו נקי.",
        src: "/brand/cinema/experience-design.jpg",
      },
      {
        word: "אורח חיים",
        line: "השעה שמסביב למשחק.",
        src: "/brand/cinema/experience-lifestyle.jpg",
      },
      {
        word: "משחק",
        line: "ארבעה על המגרש.",
        src: "/brand/cinema/experience-play.jpg",
      },
      {
        word: "חברתי",
        line: "זוגות, חברים ועוד נקודה אחת.",
        src: "/brand/cinema/experience-social.jpg",
      },
      {
        word: "פאדל",
        line: "הכדור, הקיר והקצב.",
        src: "/brand/cinema/experience-padel.jpg",
      },
      {
        word: "ערב",
        line: "משחק אחרי שהשמש שוקעת.",
        src: "/brand/cinema/experience-night.jpg",
      },
    ],
  },
  bookStrip: {
    kicker: "איך זה יעבוד",
    title: "מהטלפון למגרש.",
    body: "כך תזמינו ותשחקו כשהמועדון ייפתח.",
    steps: [
      { label: "01", title: "פותחים את האפליקציה", body: "ההרשמה וההזמנות מתבצעות מהטלפון." },
      { label: "02", title: "בוחרים שעה", body: "מגרש, יום ושעה פנויה, בכמה הקשות." },
      { label: "03", title: "מגיעים למועדון", body: "מחבטים וכדורים מחכים במקום למי שצריך." },
      { label: "04", title: "סורקים ומשחקים", body: "סריקה בכניסה למגרש, והמשחק מתחיל." },
    ],
    pending: "האפליקציה תיפתח יחד עם המועדון. עד אז אפשר לשמור מקום ברשימת הפתיחה.",
  },
  courts: {
    kicker: "המגרש",
    title: "מגרש שמרגישים בו את ההבדל.",
    body: "כל מגרש של PADELTECH נבנה לפי תקן הפדרציה הבינלאומית לפאדל (FIP). זה מה שתרגישו במשחק.",
    items: [
      {
        label: "קפיצה צפויה",
        body: "משטח ורשת מתכת לפי התקן, כך שהכדור חוזר בדיוק כמו שציפיתם.",
      },
      {
        label: "אור אחיד",
        body: "תאורה בלי אזורים חשוכים, גם במשחק ערב.",
      },
      {
        label: "מקום ללוב",
        body: "לפחות 6 מטרים פנויים מעל המגרש, כדי שכל לוב יישאר במשחק.",
      },
      {
        label: "זכוכית 12 מ״מ",
        body: "קירות מזכוכית מחוסמת שמחזירים את הכדור באופן אחיד.",
      },
    ],
    more: "לתקן המלא",
  },
  equipment: {
    kicker: "ציוד",
    title: "הציוד.",
    body: "מחבטים, תיקים וכדורים בעיצוב PADELTECH. חלק מהמועדון, לא עוד חנות ציוד.",
    prev: "תמונה קודמת",
    next: "תמונה הבאה",
    slides: [
      {
        src: "/brand/equipment/01-lineup.jpg",
        label: "Speed · Pro · Control",
        alt: "שלושה מחבטי PADELTECH — Speed, Pro ו־Control — עם תיקים, כדורים ובקבוקים",
      },
      {
        src: "/brand/equipment/02-pro.jpg",
        label: "Pro",
        alt: "מחבט PADELTECH Pro על ספסל המגרש לצד תיק, מגבת וכדורים",
      },
      {
        src: "/brand/equipment/03-kit.jpg",
        label: "הסט",
        alt: "מבט מלמעלה על מחבטי PADELTECH, תיקים, כדורים, מגבת ובקבוק",
      },
    ],
  },
  play: {
    kicker: "לשחק",
    title: "איך בא לכם לשחק?",
    intro: "ספרו לנו מה מעניין אתכם, ונעדכן כשהפעילות שמתאימה לכם תיפתח.",
    cta: "זה אני",
    items: [
      {
        interest: "beginner" as const,
        title: "פעם ראשונה?",
        body: "מכירים את המשחק, את החוקים ואת הדרך להתחיל.",
      },
      {
        interest: "social" as const,
        title: "מחפשים עם מי לשחק?",
        body: "משחקים חברתיים הם הדרך למצוא שותפים ברמה שלכם.",
      },
      {
        interest: "training" as const,
        title: "רוצים להשתפר?",
        body: "אימונים לעבודה על טכניקה, על קריאת המשחק ועל ביטחון.",
      },
      {
        interest: "court" as const,
        title: "יש לכם כבר רביעייה?",
        body: "נעדכן אתכם ברגע שאפשר יהיה להזמין מגרש.",
      },
    ],
  },
  wellness: {
    kicker: "הרגע שאחרי",
    title: "יש מקום גם לרגע שאחרי.",
    lines: "להוריד קצב, לנשום, להישאר עוד קצת.",
    body: "המועדון לא נגמר בקו האחורי. אנחנו בונים מקום שנעים להישאר בו אחרי המשחק. השירותים והמתקנים יפורסמו לכל מועדון לקראת פתיחתו.",
    cta: "על הרגע שאחרי",
  },
  groupsHome: {
    kicker: "קבוצות וארגונים",
    title: "מחליפים את חדר הישיבות במגרש.",
    body: "יום צוות, אירוע חברה או רביעייה שהפכה לקבוצה. ספרו לנו על הקבוצה, ונחזור אליכם כשנוכל להציע מועדים.",
    cta: "ספרו לנו על הקבוצה",
  },
  clubsHome: {
    kicker: "המועדון",
    title: "איפה תרצו לשחק?",
    body: "המועדון הראשון של PADELTECH בישראל בדרך. בחרו אזור, ונעדכן אתכם ראשונים כשיהיה מידע עליו.",
    disclaimer: "בחירת אזור מביעה התעניינות בלבד, ואינה מעידה על מועדון מתוכנן באותו אזור.",
  },
  signup: {
    kicker: "רשימת הפתיחה",
    title: "שמרו לכם מקום.",
    body: "השאירו פרטים, ונעדכן אתכם ראשונים על המועדון והפעילות שמעניינים אתכם.",
    name: "שם",
    email: "דוא״ל",
    region: "אזור מועדף",
    interest: "מה מעניין אתכם?",
    submit: "שמרו לי מקום",
    sending: "שומרים…",
    success:
      "תודה, שמרנו לכם מקום. נעדכן אתכם ראשונים כשיהיו פרטים על המועדון באזור שלכם.",
    required: "זהו שדה חובה",
    invalidEmail: "נא להזין כתובת דוא״ל תקינה, למשל name@mail.com",
    error: "לא הצלחנו לשמור את הפרטים. נסו שוב בעוד רגע.",
    wantsReply: "אשמח שיחזרו אליי",
    marketing: "אשמח לקבל עדכונים ודיוור מ־PADELTECH",
    phone: "טלפון (לא חובה)",
    regionPlaceholder: "בחירת אזור",
    privacyNote: "הפרטים נשמרים לפי",
    privacyLink: "מדיניות הפרטיות",
  },
  closer: {
    title: "זה לא המקום שבו שוכרים מגרש.",
    titleLine2: "זה המקום שבאים אליו לשחק.",
  },
  footer: {
    brand: "PADELTECH",
    tagline: "ישראל",
  },
  padelPage: {
    title: "המשחק הבא שלכם מתחיל כאן.",
    lead: "פאדל הוא משחק מחבט שמשחקים בדרך כלל בזוגות, במגרש מוקף קירות שהם חלק מהמשחק. הוא מחבר בין טכניקה, תזמון ועבודת צוות, ובין ארבעה אנשים שנפגשים על המגרש.",
    beginnersTitle: "חדשים במשחק? מתחילים מהבסיס.",
    beginnersBody:
      "לא צריך ניסיון בטניס כדי להתחיל לשחק פאדל. בהתחלה לומדים את ההגשה, את התנועה על המגרש, את העבודה עם בן הזוג ואת השימוש בקירות. המטרה הראשונה היא להבין את המשחק וליהנות ממנו.",
    stagesTitle: "לכל שלב יש את המשחק שלו.",
    stagesBody:
      "למתחילים, למשחק חברתי ולמי שרוצה להתאמן. הרמות, המועדים והפרטים יפורסמו לקראת הפתיחה.",
    cta: "ספרו לנו מה מתאים לכם",
  },
  wellnessPage: {
    title: "זמן לעצמכם הוא חלק מהמשחק.",
    lead: "לפעמים רוצים להוציא אנרגיה, ולפעמים רוצים להוריד קצב. במועדון של PADELTECH יש מקום לשניהם.",
    moveTitle: "תנועה",
    move: "מקום לתנועה גם מעבר למשחק עצמו.",
    recoverTitle: "התאוששות",
    recover: "מה שקורה אחרי המאמץ הוא חלק מחוויית המועדון.",
    spaceTitle: "מרחב",
    space: "מקום שנעים להישאר בו, לפגוש אנשים או לקחת רגע לעצמכם.",
    close:
      "ההיצע המדויק ייקבע לכל מועדון ויפורסם לקראת פתיחתו.",
    cta: "עדכנו אותי על הרגע שאחרי",
  },
  storyPage: {
    title: "יותר ממשחק. מקום להשתייך אליו.",
    body: "זה לא המקום שבו שוכרים מגרש. זה המקום שבאים אליו לשחק.",
    more: "PADELTECH ישראל בונה מתחמי פאדל במידות FIP, עם גג סולארי ותפעול אוטומטי. המתחם בנוי סביב מה שקורה לפני המשחק, במהלכו ואחריו.",
    principles: "לשחק · להתחבר · מועדון · קהילה · ציוד",
  },
  groupsPage: {
    title: "נפגשים מחוץ לשגרה.",
    body: "מתכננים יום צוות, מפגש של הארגון או פעילות לקבוצה? ספרו לנו עליה.",
    more: "כתבו מי אתם, כמה משתתפים צפויים, באיזה אזור ומה מטרת המפגש. נחזור אליכם עם אפשרויות כשמועדי הפתיחה יתבררו.",
    contactName: "שם איש הקשר",
    organization: "שם הארגון או הקבוצה",
    email: "דוא״ל",
    phone: "טלפון",
    participants: "מספר משתתפים משוער",
    region: "אזור מועדף",
    date: "מועד רצוי, אם ידוע",
    message: "כמה מילים על הפעילות",
    submit: "שליחת הפנייה",
    disclaimer: "שליחת הפנייה אינה הזמנה ואינה אישור זמינות.",
    success: "תודה, קיבלנו את הפנייה. נחזור אליכם עם אפשרויות כשמועדי הפתיחה יתבררו.",
  },
  partnersPage: {
    title: "יש לכם מקום?",
    titleLine2: "בואו נבדוק מה אפשר לבנות בו.",
    body: "אנחנו מחפשים שטחים ונכסים שיכולים להתאים למועדוני PADELTECH בישראל.",
    audience:
      "הפנייה מיועדת לבעלי נכסים, ליישובים, לגופים ציבוריים ולשותפים עסקיים.",
    includeTitle: "מה כדאי לצרף?",
    include: [
      "מיקום הנכס",
      "שטח משוער",
      "שטח פתוח או מבנה",
      "גובה פנוי, אם מדובר במבנה",
      "תיאור המצב הקיים",
      "פרטי איש הקשר",
      "קישור לתמונות או לתוכנית, אם יש",
    ],
    location: "מיקום הנכס",
    area: "שטח משוער",
    kind: "שטח פתוח או מבנה",
    height: "גובה פנוי, אם מדובר במבנה",
    description: "תיאור המצב הקיים",
    contactName: "שם איש הקשר",
    email: "דוא״ל",
    phone: "טלפון",
    link: "קישור לתמונות או לתוכנית",
    submit: "הציעו נכס",
    disclaimer:
      "כל הצעה נבחנת לגופה, מבחינה תכנונית, תפעולית וכלכלית.",
    success: "תודה, קיבלנו את פרטי הנכס. נבחן אותם ונחזור אליכם.",
  },
  standard: {
    kicker: "התקן",
    title: "תקן FIP.",
    titleLine2: "בלי סטיות.",
    body: "הפדרציה הבינלאומית לפאדל (FIP) קובעת פרמטרים הנדסיים מחייבים. מגרש נחשב תקני רק אם הוא עומד בכולם, ובמגרשים שאנחנו מספקים אלה המידות — במדויק.",
    glass: "הקירות במועדוני PADELTECH עשויים זכוכית מחוסמת בעובי 12 מ״מ.",
    items: [
      {
        label: "מידות נטו",
        value: "10 × 20 מ׳",
        body: "רוחב על אורך, במידות פנים. טולרנס מותר של 0.5% בלבד. הרשת חוצה את המגרש לשניים, וקווי ההגשה נמצאים 6.95 מ׳ ממנה.",
      },
      {
        label: "גובה חופשי",
        value: "6 מ׳ / 8 מ׳",
        body: "המינימום המחייב: 6 מ׳ פנויים מעל כל שטח המגרש, בלי קורות, גופי תאורה, ענפים או גג. במתקנים חדשים ובתחרויות בינלאומיות: 8 מ׳. נתון קריטי בתכנון קירוי לחורף.",
      },
      {
        label: "קירות וזכוכית",
        value: "3 מ׳ + 1 מ׳",
        body: "קיר אחורי בגובה 3 מ׳ (זכוכית מחוסמת או בטון) ומעליו מטר של רשת מתכת — 4 מ׳ בפינות. בקירות הצד, שני המטרים הראשונים הם לרוב זכוכית בגובה 3 מ׳, ואחריהם מדרגה לזכוכית בגובה 2 מ׳.",
      },
      {
        label: "רשת מתכת",
        value: "50×50 – 70.8×50 מ״מ",
        body: "רשת פלסטיק או רשת גמישה אסורות. חובה להשתמש ברשת מתכת מרותכת בעובי חוט של 1.6 עד 3 מ״מ, כדי שהכדור יקפוץ באופן צפוי ולא יעבור או ייתקע.",
      },
      {
        label: "רשת המשחק",
        value: "88 / 92 ס״מ",
        body: "אורך 10 מ׳. גובה 88 ס״מ במרכז ו־92 ס״מ בקצוות. כבל עליון בקוטר של עד 10 מ״מ, מכוסה בסרט לבן ברוחב 5–6.3 ס״מ.",
      },
      {
        label: "תאורה",
        value: "400–500 / 1,000 לוקס",
        body: "למשחק חובבים: 400–500 לוקס בפיזור אחיד. לתחרויות ולשידור: 1,000 לוקס לפחות. העמודים תמיד מחוץ לזכוכית, וגופי התאורה בגובה 6 מ׳ לפחות.",
      },
      {
        label: "משטח",
        value: "ירוק / כחול / טרקוטה",
        body: "הצבעים היחידים שמאשרת FIP לדשא סינתטי. אחרי פיזור והידוק של חול קוורץ, כדור תקני שמופל מגובה 2.54 מ׳ חייב לקפוץ לגובה 135–145 ס״מ.",
      },
    ],
  },
  clubsPage: {
    title: "המועדון הראשון",
    body: "המועדון הראשון של PADELTECH בישראל בדרך. כשנפתח יופיעו כאן המיקום, מספר המגרשים וההזמנה דרך האפליקציה.",
    emptyTitle: "בקרוב",
    formTitle: "בחרו אזור וקבלו עדכונים",
    statusActive: "פתוח",
    statusComing: "בדרך",
    book: "הזמינו מגרש",
    amenities: "מתקנים",
    hours: "שעות",
  },
  bookPage: {
    title: "כך תזמינו מגרש.",
    lead: "ההזמנות ייפתחו יחד עם המועדון הראשון. עד אז, שמרו לכם מקום ונעדכן אתכם כשאפשר יהיה להזמין.",
    formTitle: "שמרו לי מקום",
    openBooking: "המשיכו להזמנה",
  },
  privacyPage: {
    title: "מדיניות פרטיות",
    updated: "עודכן לאחרונה: ספטמבר 2026",
    intro:
      "העמוד הזה מסביר אילו פרטים אנחנו אוספים באתר PADELTECH ישראל, למה, ומה הזכויות שלכם לגביהם.",
    sections: [
      {
        title: "אילו פרטים אנחנו אוספים",
        body: "רק את מה שאתם ממלאים בטפסים: שם, דוא״ל, טלפון (אם מסרתם), אזור מועדף, תחום עניין, ובטפסי קבוצות ונכסים — גם פרטי הארגון או הנכס. איננו אוספים פרטי תשלום.",
      },
      {
        title: "למה",
        body: "כדי לעדכן אתכם על פתיחת המועדון והפעילות שביקשתם, ולחזור אליכם אם ביקשתם מענה. דיוור שיווקי נשלח רק אם סימנתם שאתם מעוניינים בו.",
      },
      {
        title: "איפה הפרטים נשמרים ולכמה זמן",
        body: "הפרטים נשמרים במערכת הפניות של PADELTECH ישראל, והגישה אליהם מוגבלת לצוות. נשמור אותם עד שתבקשו למחוק אותם, או עד שלא יהיה בהם עוד צורך.",
      },
      {
        title: "מסירה לאחרים",
        body: "איננו מוכרים את הפרטים ואיננו מוסרים אותם לצד שלישי לצורכי שיווק.",
      },
      {
        title: "הזכויות שלכם",
        body: "אפשר לבקש לעיין בפרטים, לתקן אותם, למחוק אותם או להפסיק לקבל דיוור בכל עת.",
      },
    ],
    contact: "לכל בקשה בנושא פרטיות אפשר לכתוב לנו לכתובת",
    contactFallback:
      "לכל בקשה בנושא פרטיות אפשר לפנות אלינו דרך אחד הטפסים באתר, ולציין שמדובר בבקשת פרטיות.",
  },
  v2: {
    hero: {
      eyebrow: "PADELTECH ישראל",
      title: "מתחמי פאדל שמייצרים חשמל ומנהלים את עצמם.",
      body: "גג סולארי, רכש ישיר מהיצרן ותפעול אוטומטי. אנחנו מתכננים, מקימים ומפעילים מתחמי פאדל לרשויות וליזמים.",
      primary: "בדיקת התאמה לשטח שלכם",
      secondary: "איך זה עובד",
    },
    pillars: {
      kicker: "מה אנחנו עושים אחרת",
      title: "שלושה דברים שאין במתחם רגיל.",
      items: [
        {
          key: "solar",
          title: "גג סולארי",
          body: "קירוי שמגן על המגרשים משמש ומגשם, ומייצר חשמל. ההכנסה מהחשמל מקזזת חלק מעלות המתחם, ומשחקים בו גם באוגוסט.",
        },
        {
          key: "sourcing",
          title: "ישירות מהיצרן",
          body: "אנחנו עובדים ישירות מול היצרנים, בודקים את המגרשים במפעל לפני המשלוח ומנהלים את היבוא, ההתקנה והאחריות בארץ.",
        },
        {
          key: "automation",
          title: "תפעול אוטומטי",
          body: "הזמנה ותשלום מהטלפון, כניסה בקוד ותאורה שנדלקת לפי הזמנה. כך גם מתחם של שניים–ארבעה מגרשים עובד בלי צוות קבוע.",
        },
      ],
      cta: "הפתרון המלא",
    },
    doors: {
      kicker: "עם מי אנחנו עובדים",
      title: "שלוש דרכים לעבוד איתנו.",
      items: [
        {
          key: "municipalities",
          title: "רשויות מקומיות",
          body: "מתחם פאדל לתושבים, בלי תקציב הקמה ובלי להפעיל אותו בעצמכם.",
          cta: "מודלים לרשויות",
        },
        {
          key: "developers",
          title: "יזמים ובעלי נכסים",
          body: "גג, חניון או שטח פנוי? נבדוק כמה מגרשים נכנסים ואיך הם מחזירים את עצמם.",
          cta: "בדיקת התאמה",
        },
        {
          key: "operators",
          title: "מפעילים ומועדונים",
          body: "מגרשים ישירות מהיצרן, גג סולארי ומערכת תפעול למועדון קיים או חדש.",
          cta: "מה אנחנו מספקים",
        },
      ],
    },
    stats: {
      kicker: "במספרים",
      pending: "ממתין לנתונים",
      items: [
        { value: "—", label: "מגרשים שהוקמו" },
        { value: "—", label: "מתחמים" },
        { value: "—", label: "שנות פעילות" },
        { value: "FIP", label: "המידות של כל מגרש" },
      ],
    },
    process: {
      kicker: "איך זה עובד",
      title: "מהשטח ועד המשחק הראשון.",
      body: "גורם אחד מנהל את כל הפרויקט. משך כל שלב תלוי באתר ובאישורים.",
      steps: [
        { label: "01", title: "בדיקת התאמה", body: "שטח, גובה, ייעוד, חניה וקהל. כמה מגרשים נכנסים, איזה מודל מתאים והאם הגג יכול לשאת מערכת סולארית." },
        { label: "02", title: "תכנון ואישורים", body: "תכנון המתחם והגג הסולארי, אקוסטיקה ותאורה, והגשה לוועדות." },
        { label: "03", title: "ייצור ובדיקה", body: "הזמנה ישירה מהיצרן, בדיקת איכות במפעל לפני משלוח, יבוא ושילוח." },
        { label: "04", title: "הקמה והפעלה", body: "התקנה, חיבור מערכת התפעול, פתיחה, תחזוקה ודיווח שוטף." },
      ],
    },
    playersBand: {
      kicker: "לשחקנים",
      title: "רוצים לשחק במתחם שלנו?",
      body: "בחרו אזור, ונעדכן אתכם כשמתחם נפתח בו.",
      cta: "המתחמים",
    },
    closer: {
      title: "יש לכם שטח, גג או מכרז?",
      body: "שלחו מיקום, ונחזור אליכם עם בדיקת התאמה: כמה מגרשים, איזה מודל, והאם יש מקום לגג סולארי.",
      cta: "בדיקת התאמה לשטח שלכם",
    },
    solution: {
      eyebrow: "הפתרון",
      title: "מתחם פאדל שמחזיק את עצמו.",
      lead: "רוב מתחמי הפאדל נבנים כמו לפני עשר שנים: מגרש פתוח, צוות בכל משמרת ומגרשים שנקנים דרך כמה מתווכים. אנחנו בונים אחרת, בשלוש שכבות.",
      sections: [
        {
          key: "solar",
          kicker: "01",
          title: "גג סולארי",
          lead: "מבנה קירוי מעל המגרשים, עם פאנלים סולאריים על הגג.",
          points: [
            { title: "חשמל", body: "המערכת מייצרת חשמל לצריכת המתחם, למכירה לרשת או לקיזוז מול מבני ציבור סמוכים." },
            { title: "יותר שעות משחק", body: "הגג מגן משמש, מחום ומגשם, כך שהמגרש עובד בקיץ ובחורף." },
            { title: "פחות סנוור", body: "צל אחיד על המגרש, בלי שמש בעיניים בשעות אחר הצהריים." },
          ],
          note: "היקף הייצור וההכנסה תלויים בגודל הגג, בכיוון ובהסדר מול חברת החשמל. אנחנו מחשבים אותם בבדיקת ההתאמה.",
        },
        {
          key: "sourcing",
          kicker: "02",
          title: "ישירות מהיצרן, עם אחריות בארץ",
          lead: "אנחנו מנהלים את כל שרשרת האספקה בעצמנו, מהמפעל ועד המגרש.",
          points: [
            { title: "בחירת יצרן ודגם", body: "מגרש פנורמי או קלאסי, זכוכית, דשא ותאורה, לפי המפרט ולפי התקציב." },
            { title: "בדיקה במפעל", body: "בדיקת איכות לפני משלוח, כדי שבעיה תתגלה בסין ולא באתר." },
            { title: "יבוא והתקנה", body: "שילוח, מכס, הובלה והתקנה, בניהול של גורם אחד." },
            { title: "אחריות וחלפים", body: "אחריות מול גורם ישראלי ומלאי חלפים בארץ." },
          ],
          note: "בלי שכבות תיווך, המחיר קרוב יותר למחיר היצרן, והאחריות נשארת אצלנו.",
        },
        {
          key: "automation",
          kicker: "03",
          title: "תפעול אוטומטי",
          lead: "מערכת אחת שמנהלת את המתחם, גם כשאין בו איש צוות.",
          points: [
            { title: "הזמנה ותשלום", body: "הזמנת מגרש מהטלפון, תשלום מראש וביטול לפי מדיניות." },
            { title: "כניסה בקוד", body: "קוד או ברקוד אישי שפותח את השער רק בשעה שהוזמנה." },
            { title: "תאורה לפי הזמנה", body: "האורות נדלקים לפני המשחק וכבים אחריו, בלי חשמל מבוזבז." },
            { title: "ניטור ודיווח", body: "מצלמות, התראות ודוח תפוסה והכנסות, גם לרשות." },
          ],
          note: "הנחת תושב, שעות לציבור ומחיר מפוקח מוגדרים במערכת ונאכפים אוטומטית.",
        },
      ],
      closerTitle: "רוצים לדעת אם זה מתאים לשטח שלכם?",
      closerBody: "שלחו מיקום, ונחזור אליכם עם בדיקת התאמה.",
    },
    municipalities: {
      eyebrow: "לרשויות מקומיות",
      title: "מתחם פאדל לתושבים, בלי תקציב הקמה.",
      lead: "אנחנו מתכננים, מקימים ומפעילים את המתחם, עם גג סולארי ותפעול אוטומטי. הרשות שומרת על השליטה בשעות, במחירים ובנגישות לתושבים.",
      modelsTitle: "מודלים לשיתוף פעולה",
      modelsNote: "המודל המדויק נקבע לכל רשות ולכל אתר.",
      models: [
        { name: "זיכיון להקמה והפעלה", invests: "PADELTECH", operates: "PADELTECH", gets: "דמי זיכיון שנתיים ומתחם שחוזר לרשות בסוף התקופה" },
        { name: "הקמה בשכירות", invests: "PADELTECH", operates: "PADELTECH", gets: "דמי שכירות על הקרקע או המבנה" },
        { name: "שותפות", invests: "הרשות, יחד עם PADELTECH", operates: "PADELTECH", gets: "חלק מההכנסות, לפי חלקה בהשקעה" },
        { name: "הקמה בלבד", invests: "הרשות", operates: "הרשות או מפעיל מטעמה", gets: "מתחם מוכן ומפתח ביד, עם תוכנית תחזוקה" },
      ],
      modelsHead: { name: "מודל", invests: "מי משקיע", operates: "מי מפעיל", gets: "מה הרשות מקבלת" },
      residentsTitle: "מה התושבים מקבלים",
      residents: [
        { title: "הנחת תושב", body: "מחיר מופחת לתושבי הרשות, שמוגדר במערכת ההזמנות." },
        { title: "שעות לציבור", body: "שעות קבועות לבתי ספר, לנוער ולפעילות קהילתית." },
        { title: "מגרש נגיש", body: "לפחות מגרש אחד נגיש בכל מתחם." },
        { title: "מחיר מפוקח", body: "מחיר מקסימלי לשעת מגרש, כפי שנקבע בהסכם." },
      ],
      neighboursTitle: "רעש, תאורה ושכנים",
      neighbours: "תכנון אקוסטי, תאורה מכוונת שנדלקת רק בשעות שהוזמנו, ושעות פעילות שמותאמות לשכונה. הגג הסולארי מסתיר את התאורה מלמעלה. את כל אלה אנחנו פותרים בשלב התכנון, לא אחרי התלונה הראשונה.",
      reportTitle: "הרשות רואה הכול",
      report: "דוח שוטף מתוך מערכת התפעול: תפוסה, הכנסות, שימוש של תושבים, שעות לציבור וייצור החשמל של הגג.",
      nextTitle: "מה קורה אחרי שפונים",
      next: [
        "שיחה קצרה על השטח, על הצרכים ועל לוחות הזמנים של הרשות.",
        "בדיקת התאמה: כמה מגרשים נכנסים, איזה מודל מתאים והאם יש מקום לגג סולארי.",
        "הצעה מסודרת, או ליווי בהכנת המפרט אם הרשות יוצאת למכרז.",
      ],
      faqTitle: "שאלות של רשויות",
      faq: [
        { q: "האם הרשות צריכה להשקיע כסף?", a: "בזיכיון ובהקמה בשכירות, לא. אנחנו מממנים את ההקמה ומחזירים את ההשקעה מההפעלה. בשותפות ובהקמה בלבד הרשות משקיעה, בהתאם למודל." },
        { q: "מה קורה בסוף תקופת הזיכיון?", a: "המתחם חוזר לרשות, כולל המגרשים, הגג והמערכות, לפי מה שנקבע בהסכם." },
        { q: "איך מתחם עובד בלי צוות קבוע?", a: "ההזמנה, התשלום, הכניסה והתאורה מנוהלים במערכת. המתחם מנוטר מרחוק, ויש מענה טלפוני וצוות שמגיע לתחזוקה, לאירועים ולתקלות." },
        { q: "מה קורה עם החשמל שהגג מייצר?", a: "לפי ההסדר שנבחר: צריכה עצמית של המתחם, מכירה לרשת או קיזוז מול מבני ציבור. את הפירוט אנחנו נותנים בבדיקת ההתאמה." },
        { q: "אפשר להתחיל קטן?", a: "כן. אפשר להתחיל בשניים–ארבעה מגרשים ולהוסיף מגרשים לפי הביקוש." },
        { q: "מי מתחזק את המגרשים?", a: "אנחנו, בכל המודלים שבהם אנחנו מפעילים. בהקמה בלבד המתחם נמסר עם תוכנית תחזוקה." },
        { q: "כמה זמן לוקחת הקמה?", a: "השלב הארוך הוא בדרך כלל האישורים. ייצור, משלוח והתקנה מתוכננים במקביל, ולוח הזמנים המלא ניתן בבדיקת ההתאמה." },
      ],
      formTitle: "נדבר על המתחם שלכם",
      formBody: "השאירו פרטים, ונחזור אליכם תוך יום עסקים אחד.",
    },
    operators: {
      eyebrow: "למפעילים ולמועדונים",
      title: "מגרשים, גג ומערכת תפעול, ממקור אחד.",
      lead: "למועדון קיים או חדש: מגרשים ישירות מהיצרן עם אחריות בארץ, קירוי סולארי ומערכת שמפעילה את המועדון בלי צוות בכל משמרת.",
      productsTitle: "מה אנחנו מספקים",
      products: [
        { title: "מגרשים", body: "פנורמיים או קלאסיים, פתוחים או מקורים, במידות FIP. בדיקה במפעל והתקנה בארץ." },
        { title: "גג סולארי", body: "קירוי למגרשים קיימים או חדשים, עם מערכת סולארית שמייצרת חשמל." },
        { title: "מערכת תפעול", body: "הזמנה ותשלום, כניסה בקוד, תאורה לפי הזמנה וניטור מרחוק." },
        { title: "תחזוקה וחלפים", body: "תחזוקה תקופתית, מלאי חלפים בארץ ומענה לתקלות." },
      ],
      formTitle: "בקשת הצעה",
      formBody: "ספרו לנו על המועדון או על השטח, ונחזור עם הצעה.",
    },
    developers: {
      eyebrow: "ליזמים ובעלי נכסים",
      title: "יש לכם גג, חניון או שטח פנוי?",
      lead: "מתחם פאדל עם גג סולארי ותפעול אוטומטי יכול להפוך שטח מת לנכס שמכניס. אנחנו בודקים את ההתאמה, מקימים ומפעילים, לבד או איתכם.",
      formTitle: "בדיקת התאמה לנכס",
      formBody: "ספרו לנו איפה הנכס ומה הגודל שלו, ונחזור אליכם.",
      needsTitle: "מה צריך כדי שיהיה מתחם",
      needs: [
        { title: "שטח", body: "מגרש אחד הוא 10 × 20 מ׳, ועוד שטחי מעבר, שירותים וחניה." },
        { title: "גובה", body: "במבנה: לפחות 6 מ׳ פנויים מעל המגרש, ו־8 מ׳ למתקן חדש." },
        { title: "ייעוד", body: "ייעוד קרקע שמאפשר ספורט, או הליך לשינוי שימוש." },
        { title: "גישה", body: "חניה, תחבורה ציבורית וקהל שחקנים באזור." },
      ],
    },
    projects: {
      eyebrow: "פרויקטים",
      title: "מה בנינו, ומה בדרך.",
      lead: "כאן יוצגו מתחמים שהקמנו, עם עיר, מספר מגרשים ושנה.",
      emptyTitle: "הפרויקטים יתווספו בקרוב",
      emptyBody: "עד אז, אלה הדמיות של הקונספט העיצובי. הן לא מתחמים קיימים.",
      visionTitle: "הקונספט העיצובי",
    },
    court: {
      eyebrow: "המגרש",
      title: "מגרש במידות FIP. בלי סטיות.",
      lead: "המפרט של המגרשים שאנחנו מספקים: מידות, גובה, קירות, רשת, תאורה ומשטח. כל מגרש נבדק במפעל לפני משלוח.",
    },
    about: {
      eyebrow: "אודות",
      title: "חברה ישראלית למתחמי פאדל.",
      lead: "PADELTECH ישראל מתכננת, מקימה ומפעילה מתחמי פאדל לרשויות, ליזמים ולמפעילים, עם גג סולארי, רכש ישיר מהיצרן ותפעול אוטומטי.",
      body: "התחלנו מהשאלה איך מתחם פאדל יכול לעבוד גם ביישוב קטן, בלי תקציב גדול ובלי צוות בכל משמרת. התשובה היא לא עוד מועדון, אלא מתחם שמייצר חשמל, נקנה ישירות מהיצרן ומנהל את עצמו.",
      founderTitle: "מי מוביל את PADELTECH ישראל",
      founderName: "אייל, מייסד",
      founderBody: "מהנדס תעשייה וניהול ויזם. מנהל יבוא והפצה של מערכות טכנולוגיות מסין וייצור בתקינה אירופית, ומביא את הניסיון הזה לניהול פרויקטים של פאדל, מהמפעל ועד המגרש.",
      teamTitle: "מי עומד מאחורי PADELTECH ישראל",
      teamPending: "",
    },
    contact: {
      eyebrow: "צור קשר",
      title: "בדיקת התאמה לשטח שלכם.",
      lead: "ספרו לנו מי אתם ואיפה השטח. נחזור אליכם תוך יום עסקים אחד עם השאלות הנכונות, ואחר כך עם בדיקת התאמה.",
      direct: "או ישירות",
      phone: "טלפון",
      whatsapp: "וואטסאפ",
      email: "דוא״ל",
    },
    form: {
      name: "שם מלא",
      organization: "רשות, חברה או מועדון",
      role: "תפקיד",
      email: "דוא״ל",
      phone: "טלפון",
      audience: "אני פונה בתור",
      audiences: {
        municipal: "רשות מקומית או חברה כלכלית",
        developer: "יזם או בעל נכס",
        operator: "מפעיל מועדון",
        other: "אחר",
      },
      site: "אתר או שטח מוצע, אם יש",
      message: "מה אתם מתכננים?",
      submit: "שליחה",
      success: "תודה, קיבלנו את הפרטים. נחזור אליכם תוך יום עסקים אחד.",
    },
  },
  faqTitle: "שאלות נפוצות",
  sim: "הדמיה",
  interests: {
    beginner: "היכרות עם פאדל",
    social: "משחק חברתי",
    training: "אימונים",
    court: "הזמנת מגרש לרביעייה",
    wellness: "הרגע שאחרי",
  } satisfies Record<ActivityInterest, string>,
  regionLabels: {
    center: "תל אביב והמרכז",
    sharon: "השרון",
    jerusalem: "ירושלים והסביבה",
    north: "חיפה והצפון",
    south: "באר שבע והדרום",
    other: "אזור אחר",
  } satisfies Record<Region, string>,
}

const en: typeof he = {
  meta: {
    title: "PADELTECH Israel — Padel facilities for municipalities and developers",
    description:
      "Padel facilities with a solar roof, courts direct from the manufacturer and automated operation. Design, build and operation for municipalities, developers and operators.",
  },
  nav: {
    municipalities: "Municipalities",
    developers: "Developers",
    operators: "Operators",
    projects: "Projects",
    court: "The court",
    solution: "The solution",
    clubs: "Clubs",
    about: "About",
    contact: "Contact",
    meeting: "Site check",
    business: "Business",
    players: "Players",
    company: "Company",
    padel: "Play",
    club: "The club",
    groups: "Teams & groups",
    wellness: "The hour after",
    story: "Story",
    partners: "Partners",
    privacy: "Privacy policy",
    main: "Main navigation",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    language: "עב",
    languageLabel: "עברית",
  },
  cta: {
    primary: "Save me a spot",
    book: "Book a court",
    secondary: "How it will work",
  },
  hero: {
    brand: "PADELTECH",
    eyebrow: "PADELTECH Israel",
    title: "Come to play.",
    body: "PADELTECH Israel plans, builds and operates padel facilities with a solar roof and automated operation.",
  },
  line: "Not where you rent a court. Where you come to play.",
  experience: {
    kicker: "The club",
    moments: [
      {
        word: "Design",
        line: "Glass, light and a clean line.",
        src: "/brand/cinema/experience-design.jpg",
      },
      {
        word: "Lifestyle",
        line: "The hour around the game.",
        src: "/brand/cinema/experience-lifestyle.jpg",
      },
      {
        word: "Play",
        line: "Four on court.",
        src: "/brand/cinema/experience-play.jpg",
      },
      {
        word: "Social",
        line: "Doubles, friends and one more point.",
        src: "/brand/cinema/experience-social.jpg",
      },
      {
        word: "Padel",
        line: "The ball, the wall and the pace.",
        src: "/brand/cinema/experience-padel.jpg",
      },
      {
        word: "Evening",
        line: "Playing after sunset.",
        src: "/brand/cinema/experience-night.jpg",
      },
    ],
  },
  bookStrip: {
    kicker: "How it will work",
    title: "From your phone to the court.",
    body: "This is how you will book and play once the club opens.",
    steps: [
      { label: "01", title: "Open the app", body: "Sign-up and bookings happen on your phone." },
      { label: "02", title: "Pick a time", body: "Court, day and a free slot, in a few taps." },
      { label: "03", title: "Arrive at the club", body: "Rackets and balls are waiting for anyone who needs them." },
      { label: "04", title: "Scan and play", body: "Scan at the court gate and the game begins." },
    ],
    pending: "The app opens with the club. Until then, you can save a spot on the opening list.",
  },
  courts: {
    kicker: "The court",
    title: "A court you can feel.",
    body: "Every PADELTECH court is built to the International Padel Federation (FIP) standard. This is what you will notice when you play.",
    items: [
      {
        label: "Predictable bounce",
        body: "Surface and metal mesh to spec, so the ball comes back exactly as you expect.",
      },
      {
        label: "Even light",
        body: "No dark patches, even in an evening game.",
      },
      {
        label: "Room for the lob",
        body: "At least 6 metres of clear height above the court, so every lob stays in play.",
      },
      {
        label: "12 mm glass",
        body: "Tempered glass walls that return the ball consistently.",
      },
    ],
    more: "The full standard",
  },
  equipment: {
    kicker: "Gear",
    title: "The kit.",
    body: "Rackets, bags and balls designed by PADELTECH. Part of the club, not another gear shop.",
    prev: "Previous image",
    next: "Next image",
    slides: [
      {
        src: "/brand/equipment/01-lineup.jpg",
        label: "Speed · Pro · Control",
        alt: "Three PADELTECH rackets — Speed, Pro and Control — with bags, balls and bottles",
      },
      {
        src: "/brand/equipment/02-pro.jpg",
        label: "Pro",
        alt: "PADELTECH Pro racket on a court bench with a bag, towel and balls",
      },
      {
        src: "/brand/equipment/03-kit.jpg",
        label: "The kit",
        alt: "Overhead view of PADELTECH rackets, bags, balls, a towel and a bottle",
      },
    ],
  },
  play: {
    kicker: "Play",
    title: "How do you want to play?",
    intro: "Tell us what interests you, and we will let you know when the right activity opens.",
    cta: "That's me",
    items: [
      {
        interest: "beginner",
        title: "First time?",
        body: "Get to know the game, the rules and how to start.",
      },
      {
        interest: "social",
        title: "Looking for people to play with?",
        body: "Social games are how you find partners at your level.",
      },
      {
        interest: "training",
        title: "Want to improve?",
        body: "Training for technique, reading the game and confidence.",
      },
      {
        interest: "court",
        title: "Already have a four?",
        body: "We will let you know the moment courts can be booked.",
      },
    ],
  },
  wellness: {
    kicker: "The hour after",
    title: "There is room for the hour after.",
    lines: "Slow down, breathe, stay a little longer.",
    body: "The club does not end at the back wall. We are building a place worth staying in after the game. Services and facilities will be announced for each club ahead of its opening.",
    cta: "About the hour after",
  },
  groupsHome: {
    kicker: "Teams & groups",
    title: "Swap the boardroom for a court.",
    body: "A team day, a company event, or a four that grew into a group. Tell us about yours, and we will get back to you when we can offer dates.",
    cta: "Tell us about your group",
  },
  clubsHome: {
    kicker: "The club",
    title: "Where do you want to play?",
    body: "The first PADELTECH club in Israel is on its way. Choose an area, and you will be the first to hear about it.",
    disclaimer: "Choosing an area expresses interest only. It does not mean a club is planned there.",
  },
  signup: {
    kicker: "The opening list",
    title: "Save your spot.",
    body: "Leave your details, and you will be the first to hear about the club and the activity you care about.",
    name: "Name",
    email: "Email",
    region: "Preferred area",
    interest: "What interests you?",
    submit: "Save me a spot",
    sending: "Saving…",
    success:
      "Thank you, your spot is saved. You will be the first to hear when there is news about a club in your area.",
    required: "This field is required",
    invalidEmail: "Please enter a valid email address, e.g. name@mail.com",
    error: "We could not save your details. Please try again in a moment.",
    wantsReply: "I would like someone to get back to me",
    marketing: "I would like updates and news from PADELTECH",
    phone: "Phone (optional)",
    regionPlaceholder: "Choose an area",
    privacyNote: "Your details are kept under our",
    privacyLink: "privacy policy",
  },
  closer: {
    title: "Not where you rent a court.",
    titleLine2: "Where you come to play.",
  },
  footer: {
    brand: "PADELTECH",
    tagline: "Israel",
  },
  padelPage: {
    title: "Your next game starts here.",
    lead: "Padel is a racket sport usually played in pairs, on a court enclosed by walls that are part of the game. It brings together technique, timing and teamwork — and four people who meet on court.",
    beginnersTitle: "New to the game? Start with the basics.",
    beginnersBody:
      "You do not need tennis experience to start padel. First you learn the serve, how to move, how to work with your partner and how to use the walls. The first goal is to understand the game and enjoy it.",
    stagesTitle: "Every stage has its own game.",
    stagesBody:
      "For beginners, for social play and for anyone who wants to train. Levels, dates and details will be announced ahead of opening.",
    cta: "Tell us what suits you",
  },
  wellnessPage: {
    title: "Time for yourself is part of the game.",
    lead: "Sometimes you want to burn energy, sometimes you want to slow down. A PADELTECH club has room for both.",
    moveTitle: "Move",
    move: "Room for movement beyond the match itself.",
    recoverTitle: "Recover",
    recover: "What happens after the effort is part of the club.",
    spaceTitle: "Space",
    space: "A place worth staying in, to meet people or take a moment.",
    close:
      "The exact offering will be set for each club and announced ahead of its opening.",
    cta: "Keep me posted on the hour after",
  },
  storyPage: {
    title: "More than a game. A place to belong.",
    body: "Not where you rent a court. Where you come to play.",
    more: "PADELTECH Israel builds padel facilities to FIP dimensions, with a solar roof and automated operation. Each facility is designed around what happens before, during and after the game.",
    principles: "Play · Connect · Club · Community · Gear",
  },
  groupsPage: {
    title: "Meet outside the routine.",
    body: "Planning a team day, a company gathering or a group activity? Tell us about it.",
    more: "Let us know who you are, how many people are coming, which area and what the gathering is for. We will come back to you with options once opening dates are clear.",
    contactName: "Contact name",
    organization: "Organisation or group",
    email: "Email",
    phone: "Phone",
    participants: "Expected number of people",
    region: "Preferred area",
    date: "Preferred date, if known",
    message: "A few words about the activity",
    submit: "Send inquiry",
    disclaimer: "Sending an inquiry is not a booking or a confirmation of availability.",
    success: "Thank you, we have your inquiry. We will come back to you with options once opening dates are clear.",
  },
  partnersPage: {
    title: "Have a site?",
    titleLine2: "Let's see what we can build there.",
    body: "We are looking for land and buildings that could suit PADELTECH clubs in Israel.",
    audience:
      "This page is for property owners, local communities, public bodies and business partners.",
    includeTitle: "What to include",
    include: [
      "Property location",
      "Approximate area",
      "Open land or building",
      "Clear height, if a building",
      "Current condition",
      "Contact details",
      "Link to photos or a plan, if available",
    ],
    location: "Property location",
    area: "Approximate area",
    kind: "Open land or building",
    height: "Clear height, if a building",
    description: "Current condition",
    contactName: "Contact name",
    email: "Email",
    phone: "Phone",
    link: "Link to photos or a plan",
    submit: "Propose a site",
    disclaimer:
      "Every proposal is reviewed on its planning, operational and commercial merits.",
    success: "Thank you, we have the site details. We will review them and get back to you.",
  },
  standard: {
    kicker: "The standard",
    title: "FIP standard.",
    titleLine2: "No deviation.",
    body: "The International Padel Federation (FIP) sets binding engineering parameters. A court is regulation only if it meets all of them — and the courts we supply meet these dimensions, exactly.",
    glass: "PADELTECH club walls are 12 mm tempered glass.",
    items: [
      {
        label: "Court size",
        value: "10 × 20 m",
        body: "Width by length, internal dimensions. Allowed tolerance: 0.5% only. The net divides the court in two; service lines sit 6.95 m from it.",
      },
      {
        label: "Clearance",
        value: "6 m / 8 m",
        body: "Binding minimum: 6 m clear above the whole court — no beams, luminaires, branches or roof. New facilities and international competition: 8 m. Critical when planning a winter cover.",
      },
      {
        label: "Walls & glass",
        value: "3 m + 1 m",
        body: "Back wall 3 m high (tempered glass or concrete) with 1 m of metal mesh above — 4 m at the corners. On the side walls, the first two metres are usually 3 m glass, then step down to 2 m glass.",
      },
      {
        label: "Wire mesh",
        value: "50×50 – 70.8×50 mm",
        body: "Plastic or flexible mesh is not allowed. Welded metal mesh with 1.6–3 mm wire is required, so the ball rebounds predictably and never passes through or gets stuck.",
      },
      {
        label: "The net",
        value: "88 / 92 cm",
        body: "10 m long. 88 cm high at the centre and 92 cm at the posts. Top cable up to 10 mm thick, covered with a white band 5–6.3 cm wide.",
      },
      {
        label: "Lighting",
        value: "400–500 / 1,000 lux",
        body: "Club play: 400–500 lux, evenly spread. Competition and broadcast: at least 1,000 lux. Posts always outside the glass; luminaires at least 6 m high.",
      },
      {
        label: "Surface",
        value: "Green / blue / terracotta",
        body: "The only colours FIP approves for synthetic turf. After quartz sand is spread and compacted, a regulation ball dropped from 2.54 m must bounce to 135–145 cm.",
      },
    ],
  },
  clubsPage: {
    title: "The first club",
    body: "The first PADELTECH club in Israel is on its way. When it opens, you will find its location, number of courts and in-app booking here.",
    emptyTitle: "Coming soon",
    formTitle: "Choose an area and get updates",
    statusActive: "Open",
    statusComing: "On the way",
    book: "Book a court",
    amenities: "Facilities",
    hours: "Hours",
  },
  bookPage: {
    title: "How booking will work.",
    lead: "Bookings open with the first club. Until then, save your spot and we will tell you when courts can be booked.",
    formTitle: "Save me a spot",
    openBooking: "Continue to booking",
  },
  privacyPage: {
    title: "Privacy policy",
    updated: "Last updated: September 2026",
    intro:
      "This page explains what information the PADELTECH Israel website collects, why, and what your rights are.",
    sections: [
      {
        title: "What we collect",
        body: "Only what you enter in our forms: name, email, phone (if given), preferred area and interest, and for group and property inquiries, details about the organisation or site. We do not collect payment details.",
      },
      {
        title: "Why",
        body: "To update you about the club opening and the activity you asked about, and to get back to you if you asked for a reply. Marketing emails are sent only if you opted in.",
      },
      {
        title: "Where it is kept and for how long",
        body: "Your details are kept in the PADELTECH Israel inquiry system, with access limited to our team. We keep them until you ask us to delete them, or until they are no longer needed.",
      },
      {
        title: "Sharing",
        body: "We do not sell your details or share them with third parties for marketing.",
      },
      {
        title: "Your rights",
        body: "You can ask to see, correct or delete your details, or stop receiving emails, at any time.",
      },
    ],
    contact: "For any privacy request, write to us at",
    contactFallback:
      "For any privacy request, contact us through any form on this site and mention that it is a privacy request.",
  },
  v2: {
    hero: {
      eyebrow: "PADELTECH Israel",
      title: "Padel facilities that make their own power and run themselves.",
      body: "A solar roof, courts bought direct from the manufacturer, and automated operation. We plan, build and operate padel facilities for municipalities and developers.",
      primary: "Check your site",
      secondary: "How it works",
    },
    pillars: {
      kicker: "What we do differently",
      title: "Three things a standard facility doesn't have.",
      items: [
        {
          key: "solar",
          title: "A solar roof",
          body: "A canopy that shelters the courts from sun and rain and generates electricity. The power income offsets part of the facility's cost, and you can play in August.",
        },
        {
          key: "sourcing",
          title: "Direct from the manufacturer",
          body: "We work directly with manufacturers, inspect the courts at the factory before shipping, and manage import, installation and warranty in Israel.",
        },
        {
          key: "automation",
          title: "Automated operation",
          body: "Booking and payment by phone, code entry and lights that switch on with the booking. A facility of two to four courts runs without permanent staff.",
        },
      ],
      cta: "The full solution",
    },
    doors: {
      kicker: "Who we work with",
      title: "Three ways to work with us.",
      items: [
        {
          key: "municipalities",
          title: "Municipalities",
          body: "A padel facility for residents, with no construction budget and no one to run it yourselves.",
          cta: "Models for municipalities",
        },
        {
          key: "developers",
          title: "Developers and property owners",
          body: "A roof, a car park or an empty plot? We will check how many courts fit and how they pay back.",
          cta: "Site check",
        },
        {
          key: "operators",
          title: "Operators and clubs",
          body: "Courts direct from the manufacturer, a solar roof and an operating system for a new or existing club.",
          cta: "What we supply",
        },
      ],
    },
    stats: {
      kicker: "In numbers",
      pending: "Awaiting data",
      items: [
        { value: "—", label: "Courts built" },
        { value: "—", label: "Facilities" },
        { value: "—", label: "Years of operation" },
        { value: "FIP", label: "Dimensions of every court" },
      ],
    },
    process: {
      kicker: "How it works",
      title: "From the site to the first match.",
      body: "One party runs the whole project. Each stage takes as long as the site and the permits require.",
      steps: [
        { label: "01", title: "Site check", body: "Area, height, zoning, parking and demand. How many courts fit, which model suits, and whether the roof can carry solar." },
        { label: "02", title: "Design and permits", body: "Site and solar-roof design, acoustics and lighting, and submission to the planning committees." },
        { label: "03", title: "Manufacture and inspection", body: "Direct order from the manufacturer, factory inspection before shipping, import and freight." },
        { label: "04", title: "Build and operate", body: "Installation, connecting the operating system, opening, maintenance and regular reporting." },
      ],
    },
    playersBand: {
      kicker: "For players",
      title: "Want to play at one of our facilities?",
      body: "Choose an area and we will tell you when a facility opens there.",
      cta: "Facilities",
    },
    closer: {
      title: "Have a site, a roof or a tender?",
      body: "Send us the location and we will come back with a site check: how many courts, which model, and whether there is room for a solar roof.",
      cta: "Check your site",
    },
    solution: {
      eyebrow: "The solution",
      title: "A padel facility that carries itself.",
      lead: "Most padel facilities are still built the way they were ten years ago: open courts, staff on every shift, and courts bought through several middlemen. We build differently, in three layers.",
      sections: [
        {
          key: "solar",
          kicker: "01",
          title: "A solar roof",
          lead: "A canopy over the courts, with solar panels on top.",
          points: [
            { title: "Power", body: "The system generates electricity for the facility, for sale to the grid, or to offset nearby public buildings." },
            { title: "More playing hours", body: "The roof shelters the courts from sun, heat and rain, so they work in summer and winter." },
            { title: "Less glare", body: "Even shade across the court, with no sun in the players' eyes in the afternoon." },
          ],
          note: "Output and income depend on roof size, orientation and the arrangement with the electricity company. We calculate them in the site check.",
        },
        {
          key: "sourcing",
          kicker: "02",
          title: "Direct from the manufacturer, with a warranty in Israel",
          lead: "We manage the whole supply chain ourselves, from the factory to the court.",
          points: [
            { title: "Manufacturer and model", body: "Panoramic or classic court, glass, turf and lighting, matched to the specification and the budget." },
            { title: "Factory inspection", body: "A quality check before shipping, so a problem is found at the factory and not on site." },
            { title: "Import and installation", body: "Freight, customs, delivery and installation, managed by one party." },
            { title: "Warranty and spares", body: "A warranty with an Israeli company and spare parts held in Israel." },
          ],
          note: "With no middlemen, the price is closer to the factory price, and the responsibility stays with us.",
        },
        {
          key: "automation",
          kicker: "03",
          title: "Automated operation",
          lead: "One system that runs the facility, even when no one is on site.",
          points: [
            { title: "Booking and payment", body: "Court booking by phone, payment in advance and cancellation by policy." },
            { title: "Code entry", body: "A personal code or barcode that opens the gate only at the booked time." },
            { title: "Lights on booking", body: "Lights switch on before the match and off after it, with no wasted power." },
            { title: "Monitoring and reports", body: "Cameras, alerts and an occupancy and revenue report, for the municipality too." },
          ],
          note: "Resident discounts, public hours and price caps are set in the system and enforced automatically.",
        },
      ],
      closerTitle: "Want to know if it fits your site?",
      closerBody: "Send us the location and we will come back with a site check.",
    },
    municipalities: {
      eyebrow: "For municipalities",
      title: "A padel facility for residents, with no construction budget.",
      lead: "We plan, build and operate the facility, with a solar roof and automated operation. The municipality keeps control of hours, prices and access for residents.",
      modelsTitle: "Partnership models",
      modelsNote: "The exact model is set for each municipality and each site.",
      models: [
        { name: "Build-and-operate concession", invests: "PADELTECH", operates: "PADELTECH", gets: "An annual concession fee, and the facility returns at the end of the term" },
        { name: "Lease and build", invests: "PADELTECH", operates: "PADELTECH", gets: "Rent for the land or the building" },
        { name: "Partnership", invests: "The municipality and PADELTECH together", operates: "PADELTECH", gets: "A share of revenue, in line with its share of the investment" },
        { name: "Build only", invests: "The municipality", operates: "The municipality or its operator", gets: "A turnkey facility with a maintenance plan" },
      ],
      modelsHead: { name: "Model", invests: "Who invests", operates: "Who operates", gets: "What the municipality gets" },
      residentsTitle: "What residents get",
      residents: [
        { title: "Resident discount", body: "A lower price for residents, set in the booking system." },
        { title: "Public hours", body: "Fixed hours for schools, youth and community activity." },
        { title: "Accessible court", body: "At least one accessible court in every facility." },
        { title: "Capped price", body: "A maximum court-hour price, as set in the agreement." },
      ],
      neighboursTitle: "Noise, lighting and neighbours",
      neighbours: "Acoustic design, directed lighting that is on only during booked hours, and opening hours that suit the neighbourhood. The solar roof screens the lights from above. We solve all of this at the design stage, not after the first complaint.",
      reportTitle: "The municipality sees everything",
      report: "A regular report from the operating system: occupancy, revenue, resident use, public hours and the roof's power output.",
      nextTitle: "What happens after you get in touch",
      next: [
        "A short call about the site, your needs and the municipality's timeline.",
        "A site check: how many courts fit, which model suits, and whether there is room for a solar roof.",
        "A proposal, or support in drafting the specification if the municipality goes to tender.",
      ],
      faqTitle: "Questions from municipalities",
      faq: [
        { q: "Does the municipality need to invest?", a: "Under a concession or a lease-and-build, no. We fund construction and recover it from operation. In a partnership or build-only model the municipality invests, according to the model." },
        { q: "What happens at the end of the concession?", a: "The facility returns to the municipality, including the courts, the roof and the systems, as set in the agreement." },
        { q: "How does a facility run without permanent staff?", a: "Booking, payment, entry and lighting are handled by the system. The facility is monitored remotely, with phone support and a team that comes in for maintenance, events and faults." },
        { q: "What happens to the power the roof generates?", a: "Depending on the arrangement: used by the facility, sold to the grid, or offset against public buildings. We give the details in the site check." },
        { q: "Can we start small?", a: "Yes. You can start with two to four courts and add more as demand grows." },
        { q: "Who maintains the courts?", a: "We do, in every model where we operate. In build-only, the facility is handed over with a maintenance plan." },
        { q: "How long does it take to build?", a: "Permits are usually the longest stage. Manufacture, shipping and installation are planned in parallel, and the full timeline comes with the site check." },
      ],
      formTitle: "Let's talk about your facility",
      formBody: "Leave your details and we will get back to you within one business day.",
    },
    operators: {
      eyebrow: "For operators and clubs",
      title: "Courts, roof and operating system, from one source.",
      lead: "For a new or existing club: courts direct from the manufacturer with a warranty in Israel, a solar canopy, and a system that runs the club without staff on every shift.",
      productsTitle: "What we supply",
      products: [
        { title: "Courts", body: "Panoramic or classic, open or covered, to FIP dimensions. Factory-inspected and installed in Israel." },
        { title: "Solar roof", body: "A canopy for new or existing courts, with a solar system that generates electricity." },
        { title: "Operating system", body: "Booking and payment, code entry, lights on booking and remote monitoring." },
        { title: "Maintenance and spares", body: "Scheduled maintenance, spare parts in Israel and fault response." },
      ],
      formTitle: "Request a proposal",
      formBody: "Tell us about your club or site and we will come back with a proposal.",
    },
    developers: {
      eyebrow: "For developers and property owners",
      title: "Have a roof, a car park or an empty plot?",
      lead: "A padel facility with a solar roof and automated operation can turn dead space into an earning asset. We check the fit, build and operate, on our own or with you.",
      formTitle: "Site check for your property",
      formBody: "Tell us where the property is and how large it is, and we will get back to you.",
      needsTitle: "What a facility needs",
      needs: [
        { title: "Area", body: "One court is 10 × 20 m, plus circulation, facilities and parking." },
        { title: "Height", body: "Indoors: at least 6 m clear above the court, and 8 m for a new facility." },
        { title: "Zoning", body: "Land use that allows sport, or a change-of-use process." },
        { title: "Access", body: "Parking, public transport and players in the area." },
      ],
    },
    projects: {
      eyebrow: "Projects",
      title: "What we built, and what is on the way.",
      lead: "Facilities we have built will be listed here, with city, court count and year.",
      emptyTitle: "Projects will be added soon",
      emptyBody: "Until then, these are visualizations of the design concept. They are not existing facilities.",
      visionTitle: "The design concept",
    },
    court: {
      eyebrow: "The court",
      title: "Built to FIP dimensions. No deviation.",
      lead: "The specification of the courts we supply: dimensions, height, walls, mesh, lighting and surface. Every court is inspected at the factory before shipping.",
    },
    about: {
      eyebrow: "About",
      title: "An Israeli padel facilities company.",
      lead: "PADELTECH Israel plans, builds and operates padel facilities for municipalities, developers and operators, with a solar roof, courts direct from the manufacturer and automated operation.",
      body: "We started with one question: how can a padel facility work in a small town, without a big budget and without staff on every shift? The answer is not another club, but a facility that makes its own power, is bought direct from the factory, and runs itself.",
      founderTitle: "Who leads PADELTECH Israel",
      founderName: "Eyal, founder",
      founderBody: "Industrial and management engineer and entrepreneur. He runs the import and distribution of technology systems from China and production to European certification, and brings that experience to padel projects, from the factory to the court.",
      teamTitle: "Who is behind PADELTECH Israel",
      teamPending: "",
    },
    contact: {
      eyebrow: "Contact",
      title: "A site check for your location.",
      lead: "Tell us who you are and where the site is. We will get back to you within one business day with the right questions, and then with a site check.",
      direct: "Or directly",
      phone: "Phone",
      whatsapp: "WhatsApp",
      email: "Email",
    },
    form: {
      name: "Full name",
      organization: "Municipality, company or club",
      role: "Role",
      email: "Email",
      phone: "Phone",
      audience: "I am contacting you as",
      audiences: {
        municipal: "A municipality or municipal company",
        developer: "A developer or property owner",
        operator: "A club operator",
        other: "Other",
      },
      site: "Proposed site or area, if any",
      message: "What are you planning?",
      submit: "Send",
      success: "Thank you, we have your details. We will get back to you within one business day.",
    },
  },
  faqTitle: "Frequently asked questions",
  sim: "Visualization",
  interests: {
    beginner: "Getting to know padel",
    social: "Social play",
    training: "Training",
    court: "Booking a court for a four",
    wellness: "The hour after",
  },
  regionLabels: {
    center: "Tel Aviv and the centre",
    sharon: "Sharon",
    jerusalem: "Jerusalem area",
    north: "Haifa and the north",
    south: "Be’er Sheva and the south",
    other: "Other area",
  },
}

const dictionaries = { he, en }

export type Copy = typeof he

export function getCopy(locale: Locale): Copy {
  return dictionaries[locale]
}
